services:
  dokumentor:
    image: ghcr.io/thehijacker/dokumentor:latest
    container_name: dokumentor
    ports:
      - "5123:5000"
    restart: unless-stopped
    environment:
      - "APP_SECRET_KEY=random_32_character_secret_key"
      # Enable user registration
      - "ENABLE_REGISTRATION=true"
      # Optional debug messages
      - "APP_DEBUG=false"
      # To run on insecure http ports set to false
      # NOT RECOMMENDED FOR PRODUCTION USE
      - "APP_SECURE_COOKIES=true"
      # Optional overrides for internal folder paths
      - "DATABASE_PATH=/app/data/documents.db"
      - "DOCUMENTS_PATH=/app/documents"
      # OCR languages
      - "OCR_DEFAULT_LANGUAGES=slv,eng"
      # Optional - global passwords as fallback
      - "PDF_DECRYPT_PASSWORDS=123456,ABCDEF"
      # Watch folder settings
      - "WATCH_FOLDER_ENABLED=true"
      - "WATCH_FOLDER=/app/watch_folder/"
      # AI
      - "AI_PROVIDER=internal"
      - "AI_MODEL=-simple"
      - "OPENAI_API_KEY="
      - "OLLAMA_URL=http://localhost:11434"
      - "OLLAMA_MODEL=llama2"
    volumes:
      - ./data:/app/data
      - ./documents:/app/documents
      - ./watch_folder:/app/watch_folder
      - ./logs:/app/logs